[project]
name = "ai-chatbot"
version = "0.1.0"
description = "A Streamlit-based AI chatbot using Google Generative AI."
dependencies = [
    "streamlit",
    "langchain-google-genai",
    "python-dotenv"
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"
